# Welcome to NumPy tutorial

In [1]:
import numpy as np


In [2]:
myarr = np.array([3,6,32,67],np.int64)

In [3]:
#myarr[0,1]
#it's because there is no item on [0,1] 
#bcz it's a one dimensional array
# wee need provide 2 dimensional array

In [4]:
# we are creating it 2 dimansional array using another []
myarr = np.array([[3,6,32,67]],np.int64)

In [5]:
myarr[0]


array([ 3,  6, 32, 67], dtype=int64)

In [6]:
myarr[0,1]

6

In [7]:
myarr.shape
# this array is 1x4 array means 1 row and 4 columns

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
# changing element
myarr[0,1] = 45

In [10]:
myarr

array([[ 3, 45, 32, 67]], dtype=int64)

# Array creation methds
# -------------------------------

## 1.Array creation : Conversion from other Python structures (i.e. lists and tuples)

In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype


dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({32,23,45})
#dtype is object

array({32, 45, 23}, dtype=object)

# Array creation : 2.Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [17]:
zeros = np.zeros((2,5))
# it will create a 2x5 array with all element is zero

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype


dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
  rng = np.arange(15)
    # arange is equivalent to python range
    #it's giving element from 0 to n-1

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
rng.dtype

dtype('int32')

In [24]:
rng.shape

(15,)

In [25]:
rng.size

15

In [26]:
lspace = np.linspace(1,5,12)
# linspace --> linearspace
# it will give us 1 to 5 with equally linearly space 12 elements

In [27]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [28]:
lspace = np.linspace(1,4,4)

In [29]:
lspace

array([1., 2., 3., 4.])

In [30]:
lspace.dtype

dtype('float64')

In [31]:
emp = np.empty((4,6))
#it will create the 4x6 empty array with random element but later u can modify all. 

In [32]:
emp

array([[8.79194731e-312, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 8.90104238e-307, 1.16095484e-028],
       [1.27616420e-152, 7.35167805e+223, 8.03272528e-096,
        5.09886857e-138, 5.26520936e+170, 6.72781938e+199],
       [5.26520943e+170, 2.43567292e-152, 2.49970344e+262,
        2.31859154e+251, 1.49005471e+195, 7.87265972e+276],
       [2.47510236e+214, 1.27616420e-152, 3.81187276e+180,
        8.93176404e+271, 4.98131536e+151, 9.69385786e-067]])

In [33]:
emp_like = np.empty_like(lspace)
# it will copy of lspace array size and create a empty array.
#it is uses for efficieny proposes.

In [34]:
emp_like

array([1., 2., 3., 4.])

In [35]:
ide = np.identity(45)
#identity array

In [36]:
ide


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [37]:
ide.shape

(45, 45)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
#we can reshape it like 1x99 will be eplace to 3x33
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr.shape

(3, 33)

In [42]:
#if i create 3,31 then it will give me error.
#ar.reshape(3,31)


In [43]:
#we can retain previous shape of array .
# 0/p as 1-d array
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

# array axis understanding


In [45]:
x =[[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar = np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T
#.T will transpose the whole array
#means all row convert to column and vicevesa

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat
#it will give the iterator object an dwe can iterator each item

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim
# it will give the dimension of array

2

In [54]:
ar.size

9

In [55]:
ar.nbytes
# total bytes consume by array

36

In [56]:
#creating one dimensional array
one = np.array([1,3,4,634,2])

In [57]:
one.argmax()
# gives the index of max-element

3

In [58]:
one.argmin()
# gives the index of min-element

0

In [59]:
one.argsort()
# gives the index of sorted element

array([0, 4, 1, 2, 3], dtype=int64)

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar.argmin()

8

In [62]:
ar.argmax()

6

In [63]:
ar.argmax(axis = 0)
# it's calculation on row basis bcz axis is 0

array([2, 1, 1], dtype=int64)

In [64]:
ar.argmax(axis=1)
# it's calculated on column basics bcz axis is 1

array([2, 2, 0], dtype=int64)

In [65]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [66]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [67]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2 = np.array([[1, 2, 3],
       [4, 0, 6],
       [8, 1, 0]])

# matrix operation

In [70]:
ar+ar2
# it will add each element by elemet of 2 arrays

array([[ 2,  4,  6],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
ar*ar2
# multiply element wise od 2 arrays

array([[ 1,  4,  9],
       [16,  0, 36],
       [56,  1,  0]])

In [72]:
np.sqrt(ar)
# square root of each elemet of an array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [73]:
ar.sum()
# sum of all elements of the array

29

In [74]:
ar.max()
# give maximum element

7

In [75]:
ar.min()
# min element of an array

0

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
# search element
np.where(ar>5)
# row 1 index 2 element is 6 > 5 and row 2 index 0 element 7 >5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [80]:
type(np.where(ar>5))
# it gives the tuple

tuple

In [81]:
np.count_nonzero(ar)

8

In [82]:
np.nonzero(ar)
# it will give tuple of each dimension (row,column)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [85]:
ar[1,2] = 0
# i set 1,2 =0 means it will omit from above list

In [84]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

# checking python array and numpy array which takes less space

In [87]:
import sys

In [88]:
py_ar = [0,4,55,2]

In [89]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

112

In [91]:
np_ar.itemsize * np_ar.size

16

In [92]:
# so proved that numpy array takes less space according to python
# array , numpy array fast.

In [93]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a new masked array from scratch.
nu

In [96]:
# link for all numpy attribute and functions
#https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html

In [98]:
np_ar.tolist()
# it will returns alist of that array

[0, 4, 55, 2]