# Welcome to NumPy tutorial

In [1]:
import numpy as np


In [2]:
myarr = np.array([3,6,32,67],np.int64)

In [3]:
#myarr[0,1]
#it's because there is no item on [0,1] 
#bcz it's a one dimensional array
# wee need provide 2 dimensional array

In [4]:
# we are creating it 2 dimansional array using another []
myarr = np.array([[3,6,32,67]],np.int64)

In [5]:
myarr[0]


array([ 3,  6, 32, 67], dtype=int64)

In [6]:
myarr[0,1]

6

In [7]:
myarr.shape
# this array is 1x4 array means 1 row and 4 columns

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [9]:
# changing element
myarr[0,1] = 45

In [10]:
myarr

array([[ 3, 45, 32, 67]], dtype=int64)

# Array creation methds
# -------------------------------

## 1.Array creation : Conversion from other Python structures (i.e. lists and tuples)

In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype


dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({32,23,45})
#dtype is object

array({32, 45, 23}, dtype=object)

# Array creation : 2.Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [17]:
zeros = np.zeros((2,5))
# it will create a 2x5 array with all element is zero

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype


dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
  rng = np.arange(15)
    # arange is equivalent to python range
    #it's giving element from 0 to n-1

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
rng.dtype

dtype('int32')

In [24]:
rng.shape

(15,)

In [25]:
rng.size

15

In [26]:
lspace = np.linspace(1,5,12)
# linspace --> linearspace
# it will give us 1 to 5 with equally linearly space 12 elements

In [27]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [28]:
lspace = np.linspace(1,4,4)

In [29]:
lspace

array([1., 2., 3., 4.])

In [30]:
lspace.dtype

dtype('float64')

In [33]:
emp = np.empty((4,6))
#it will create the 4x6 empty array with random element but later u can modify all. 

In [32]:
emp

array([[9.63508864e-312, 7.55920438e-322, 0.00000000e+000,
        0.00000000e+000, 8.90104238e-307, 1.16095484e-028],
       [1.27616420e-152, 7.35167805e+223, 8.03272528e-096,
        5.09886857e-138, 5.26520936e+170, 6.72781938e+199],
       [5.26520943e+170, 2.43567292e-152, 2.49970344e+262,
        7.65339167e+228, 1.45913393e-152, 3.03387744e-152],
       [7.87915114e+276, 4.63991706e-072, 6.19633416e+223,
        6.32672818e+180, 4.74483502e+170, 1.24714799e-047]])

In [36]:
emp_like = np.empty_like(lspace)
# it will copy of lspace array size and create a empty array.
#it is uses for efficieny proposes.

In [35]:
emp_like

array([1., 2., 3., 4.])

In [40]:
ide = np.identity(45)
#identity array

In [38]:
ide


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [39]:
ide.shape

(45, 45)

In [41]:
arr = np.arange(99)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [73]:
#we can reshape it like 1x99 will be eplace to 3x33
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [72]:
arr.shape

(3, 33)

In [70]:
#if i create 3,31 then it will give me error.
#ar.reshape(3,31)


In [77]:
#we can retain previous shape of array.
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [78]:
arr.shape

(99,)